"use client";

import React from "react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ShieldCheck, Lock } from "lucide-react";

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      
      <main className="flex-grow max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 page-fade-in text-zinc-600 dark:text-zinc-300 leading-relaxed">
        <div className="text-center mb-12 border-b border-zinc-200 dark:border-zinc-800 pb-8">
          <div className="inline-flex items-center justify-center p-3 rounded-full bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 mb-4">
            <ShieldCheck className="w-8 h-8" />
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-white">Privacy Policy</h1>
          <p className="mt-2 text-zinc-400 text-xs uppercase tracking-wider">Last updated: June 2026</p>
        </div>

        <div className="space-y-8 text-sm sm:text-base">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-zinc-900 dark:text-white flex items-center">
              <Lock className="w-5 h-5 mr-2 text-indigo-500" />
              1. Secure File & Document Retention Policy
            </h2>
            <p>
              Your privacy and document security are our highest priority. All PDF documents, spreadsheets, slides, and photographs uploaded to our platform are stored securely in encrypted buckets on Firebase Storage.
            </p>
            <p className="bg-indigo-50 dark:bg-indigo-950/15 border border-indigo-100 dark:border-indigo-900/30 p-4 rounded-xl text-zinc-600 dark:text-zinc-300 text-xs">
              <strong>Auto-Deletion Policy:</strong> To prevent data accumulation, all uploaded documents, designs, and temporary files associated with standard prints are **automatically deleted** from our storage servers 15 days after the order is marked as "Delivered" or "Cancelled".
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-zinc-900 dark:text-white flex items-center">
              2. Information We Collect
            </h2>
            <p>
              We collect information necessary to authenticate accounts, coordinate deliveries, and verify payments:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-zinc-500">
              <li><strong>Personal Data:</strong> Display name, email address, password hash, delivery address, and telephone number.</li>
              <li><strong>Payment Data:</strong> Payment transaction identifiers generated by Stripe or Razorpay. We do NOT store full card numbers or bank credentials on our servers.</li>
              <li><strong>Usage Metrics:</strong> Browser information, viewport dimensions, pages visited, and IP addresses to optimize our UI layout.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-zinc-900 dark:text-white flex items-center">
              3. Who Accesses Your Files
            </h2>
            <p>
              Our printing operations staff (Admins) only access files to review page specifications (e.g., verifying page count matches invoice) and load them into printing queue software. Your documents are never distributed, sold, or shared with third-party advertisers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-zinc-900 dark:text-white flex items-center">
              4. Cookies and Local Sessions
            </h2>
            <p>
              We use functional cookies and `localStorage` to keep your authentication state active, store your shopping cart preferences, and maintain files selected for print customization during your browser session. You can manage cookies directly in your browser settings.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </>
  );
}
